# Generated by Django 5.0.7 on 2024-07-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_id',
        ),
    ]
