# Generated by Django 5.0.7 on 2024-07-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0003_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='msg',
        ),
    ]
