# Generated by Django 5.0.7 on 2024-07-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0004_rename_message_contactus_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
