# Generated by Django 5.0.7 on 2024-07-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0006_userdata2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='date_time',
        ),
    ]
