# Generated by Django 5.0.7 on 2024-07-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0008_alter_userdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData2',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
