# Generated by Django 5.0.7 on 2024-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0011_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('registration_num', models.CharField(max_length=100)),
                ('business_email', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(max_length=250, upload_to='static/profile_photo/')),
            ],
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='certificate',
            field=models.ImageField(max_length=250, upload_to='static/service_photo/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_image',
            field=models.ImageField(max_length=250, upload_to='static/service_photo/'),
        ),
    ]
