# Generated by Django 5.0.7 on 2024-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0012_profileview_alter_servicedetail_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileview',
            name='profile_pic',
        ),
    ]
