# Generated by Django 5.0.7 on 2024-08-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0013_remove_profileview_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetail',
            old_name='service_warranty',
            new_name='payment_methods',
        ),
    ]
