# Generated by Django 5.0.7 on 2024-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0014_rename_service_warranty_servicedetail_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
