# Generated by Django 5.0.7 on 2024-08-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0016_servicedetail_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='vendor_id',
        ),
    ]
