# Generated by Django 5.0.7 on 2024-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0017_remove_servicedetail_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='_new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
