# Generated by Django 5.0.7 on 2024-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0018_servicedetail__new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='_new_price',
            field=models.IntegerField(),
        ),
    ]
