# Generated by Django 5.0.7 on 2024-11-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0021_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
