# Generated by Django 5.0.7 on 2024-12-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFix', '0023_alter_checkout_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='area',
        ),
    ]
